<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
*	#classname#.php
*	#classname# Controller generated by AdgenMaker
*	@author Dante.leonardo
*	@version 0.1 beta
*	@link http://www.leonardopereira.com
*/

require APPPATH."controllers/application_controller.php";

class #classname# extends ApplicationController {

	function __construct()
	{
		parent::Controller();	
	}
	
	#functions#
	
}

/* End of file #filename# */
/* Location: ./system/application/controllers/#filename# */