<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
*	#filename#.php
*	Helper generated by AdgenMaker
*	@author Dante.leonardo
*	@version 0.1 beta
*	@link http://www.leonardopereira.com
*/

#functions#

/* End of file #filename# */
/* Location: ./system/application/helpers/#filename# */