<?PHP

/**
* To install this migration, run 'script/migrate.php'
* Generated by AdgenMaker
* Created by Leonardo Pereira (www.leonardopereira.com)
*/

class #classname#
	{
		function up()
		{
			
			$sql[]			= #up#
							
			return $sql;
		}
		
		function down()
		{
			$sql[]			= #down#
			return $sql;	
		}
	}
		
/* End of file #datetime#_#filename#.php */
/* Location: ./system/migrate/#datetime#_#filename#.php*/