<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
*	#classname#.php
*	Unit Model Test generated by AdgenMaker
*	@author Dante.leonardo
*	@version 0.1 beta
*	@link http://www.leonardopereira.com
*/

class #classname# extends CodeIgniterUnitTestCase {
		
	var $ci;

	function __construct()
	{
		parent::UnitTestCase();
		$this -> ci =& get_instance();
		$this->ci->load->library('fixtures');
	}
	
	function testMyFunction()
	{
		$this -> assertTrue('true');
	}
	
}
		
/* End of file #filename# */
/* Location: ./system/application/tests/models/#filename# */