<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
*	#classname#.php
*	DataMapper Model generated by AdgenMaker
*	@author Dante.leonardo
*	@version 0.1 beta
*	@link http://www.leonardopereira.com
*/

require APPPATH."models/datamagipper.php";

class #classname# extends DataMagipper
	{
		
		/* #classname# table reference */
		var $table			= "#tablename#";
		
		#hasone#
		#hasmany#
		#acceptsnestedattributesfor#
		
		#validation#
		
		function __construct($data = array())
			{
				parent::__construct($data);
			}
		
	}
		
/* End of file #filename# */
/* Location: ./system/application/models/#filename# */