<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
*	render_helper.php
*	Helper generated by AdgenMaker
*	@author Dante.leonardo
*	@version 0.1 beta
*	@link http://www.leonardopereira.com
*/


if (!function_exists('render')) 
{
	function render($file, $vars = array())
	{
		
		foreach ($vars as $key => $value) 
		{
			if($key == 'collect')
			{
				$multiple	= $vars[$key];
				unset($vars[$key]);
			}
		}
		
		$ci		=& get_instance();
		
		if (!$multiple) 
		{
			$ci -> load -> view($file, $vars);
		}
		else 
		{
			foreach ($multiple as $obj) 
			{
				$_view		= explode("/", $file);
				if(count($_view) == 0)
					$_view	= $file;
				else
					$_view	= end($_view);
					
				$_vars[$_view] = $obj;
				
				$_vars		= $vars + $_vars;
				
				$ci -> load -> view($file, $_vars);
				unset($_vars);
			}
		}
	}
}

/* End of file render_helper.php */
/* Location: ./system/application/helpers/render_helper.php */